### ISSUE TITLE
Create a statistics handler (/stats?)

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-push#1]
It would be of interest to see on an information page:
* The current number of registered devices
* The current number of total messages queued
* The current number of messages queued / device
* The number of messages received / s for the last 5min average
* The number of messages sent / s for the last 5min average

Later, maybe extend this to daily/weekly/monthly/yearly view

**Comment by dpniel** [comment]
Nice idea. Should it be an authenticated endpoint or open to the world?

**Comment by Flohack74** [comment]
We could have an option for allowed IP addies, for for the moment it can be open, too. I dont see critical information here.

**Comment by UniversalSuperBox** [comment]
This issue has been imported to GitLab as https://gitlab.com/ubports/core/lomiri-push-service/-/issues/1. Any further discussion should happen there.
