### ISSUE TITLE
"actions" in notification card does not work

### ISSUE THREAD

**Issue by krille-chan** [ubports/ubuntu-push#13]
Hello, I hope you can help me. First, I want to thank you for your hard work!!
In the documentation there is a property called "actions" which should be an array of strings with actions, like an url. Unfortunately this seems not working. I have found no examples, how to use this feature. Is this a bug or am I using this wrong?

notifydata.data.notification.card = {
                            "actions": ["appid://fluffychat.christianpauly/fluffychat"],
                            "summary": notification.room_name || notification.sender_display_name || notification.sender,
                            "body": body,
                            "persist": true,
                            "popup": true
                        }

**Comment by dpniel** [comment]
You almost have it right. :-) Your just missing current-user-version from the url so 

```js
"actions": ["appid://fluffychat.christianpauly/fluffychat/current-user-version"]
```

This is documented in the push-client docs. see [Helper output format](https://docs.ubuntu.com/phone/en/platform/guides/push-notifications-client-guide) section. And the [Url Dispatcher guide](https://docs.ubuntu.com/phone/en/platform/guides/url-dispatcher-guide) for the different urls you can provide.

**Comment by krille-chan** [comment]
God damn! I thought I have to replace "current-user-version" with the current version or with "" :D thank you very much!! Now the notification bubbles are clickable!
