### ISSUE TITLE
Brodcast Messages

### ISSUE THREAD

**Issue by ghost** [ubports/ubuntu-push#18]
Good morning.

In some cases it would be very helpful to be able to send a notification to all active push clients.

For example, I would think of this as a case when a very important update for an app is coming up, so I have the opportunity to remind everyone to quickly update it.

Here it would be of advantage, if I did not have to first look for all tokens from a database but simply send a broadcast to all clients.

**Comment by Flohack74** [comment]
Actually there is already an endpoint listening on `https://push.ubports.com/broadcast` (you can try to open it :)) but I doubt it works fully. Would need some testing to see what happens. The endpoint was used for OTA update notifications only in the past.

**Comment by hallyn** [comment]
I'm considering using conn .SetDeadline(), but that seems easy to do wrong as it appears all code has to update it. (sorry, posted this to the wrong issue somehow )

**Comment by UniversalSuperBox** [comment]
This issue has been moved to https://gitlab.com/ubports/core/lomiri-push-service/-/issues/18. Any further discussion should happen there.
