### ISSUE TITLE
Ubuntu push notifications delayed

### ISSUE THREAD

**Issue by hallyn** [ubports/ubuntu-push#22]
I'm using the push.ubports.com service (as per https://s3hh.wordpress.com/2019/09/20/first-experience-with-ubuntu-touch/).  Sometimes it takes a long time after my server says it has sent a message, before the phone gets it.  Sometimes it's instantaneous, or 3 minutes, or 45 minutes.

Is this the right place to report this?  What phone logfiles should I provide?

Any ability for ubuntu members to log into and look around some config and log files on the backend server?  (Assume not, but worth asking)

**Comment by dobey** [comment]
How is the phone connected to network? You can check the `~/.cache/upstart/ubuntu-push-client.log` to see if there's any more details. It might container personal info, so don't just post it on here.

The server is entirely under control of UBports, so @Flohack74 for example can perhaps look at server logs if necessary.

From my experience testing push in a VM and with my Nexus 4 on WiFi, I've never noticed any particular lag in notifications arising, though. However, if the network connection is unstable, the push client will keep trying to reconnect, with a backoff timeout, which may cause the increased delays at times.

**Comment by Flohack74** [comment]
In general the connection works pretty fast, but as Rodney says, minor interruptions can cause long delays since our retry intervals seem to get longer and longer. For example if your often changing to/from WiFi networks the push client is not notified about this and will timeout on the IP address first before retrying etc. I will try to look up if this is configurable, so you could try to reduce them first to see if that helps.

**Comment by hallyn** [comment]
I keep wifi off (because fallback to cellular when wifi drops is unreliable), so it's always connected over cellular to consumer cellular (at&t network).  I do not notice network outages when this happens, but I do tend to not be using the phone (i.e. walking around with it in my pocket), so it's possible.

The current ubuntu-push-client.log currently only has one line in it, saying INFO connectivity check pased.  The older ones do have som eerorrs, including "ERROR session error'ed out with read tcp...  use of closed network connection'.  Next time I notice this happening (which won't be until tomorrow afternoon as phone will be off) I'll look for the most recent error messages, thanks.

**Comment by hallyn** [comment]
My server sent push notifications at 
Sending at Tue Oct 29 10:14:07 2019: New messages:
Sending at Tue Oct 29 11:15:58 2019: New messages:
Sending at Tue Oct 29 11:16:43 2019: New messages:
Sending at Tue Oct 29 11:17:13 2019: New messages:
Sending at Tue Oct 29 11:19:59 2019: New messages:
Sending at Tue Oct 29 11:41:16 2019: New messages:

The 10:14am notification came through, but was the last one.  After that,

** (process:3451): WARNING **: a source with id 'postal' doesn't exist
2019/10/29 10:25:44.314474 INFO connectivity check passed.
2019/10/29 10:55:41.368047 INFO connectivity check passed.
2019/10/29 11:27:03.766639 ERROR session error'ed out with read tcp 10.91.118.101:39683->188.166.175.79:5001: i/o timeout
2019/10/29 11:27:06.712405 INFO unicast app:pushclient.christianpauly_pushclient msg:ZH8aIvpnEemFb4Z7KvMZ8A== payload:{"notification":{"card":{"icon":"notification","body":"New messages:\n['from \"XXX\" \u003cXXX\u003e about YYY']","summary":"New mail","popup":true,"persist":true},"vibrate":true,"sound":true}}
2019/10/29 11:27:06.713747 INFO unicast app:pushclient.christianpauly_pushclient msg:f29kTPpnEemFb4Z7KvMZ8A== payload:{"notification":{"card":{"icon":"notification","body":"New messages:\n['from \"XXX\" \u003cXXX\u003e about YYY']","summary":"New mail","popup":true,"persist":true},"vibrate":true,"sound":true}}
2019/10/29 11:27:06.730259 INFO unicast app:pushclient.christianpauly_pushclient msg:kWm6TfpnEemFb4Z7KvMZ8A== payload:{"notification":{"card":{"icon":"notification","body":"New messages:\n['from \"XXX\" \u003cXXX\u003e about YYY']","summary":"New mail","popup":true,"persist":true},"vibrate":true,"sound":true}}
2019/10/29 11:27:06.730473 INFO unicast app:pushclient.christianpauly_pushclient msg:8/ynoPpnEemFb4Z7KvMZ8A== payload:{"notification":{"card":{"icon":"notification","body":"New messages:\n['from \"XXX\" \u003cXXX\u003e about YYY']","summary":"New mail","popup":true,"persist":true},"vibrate":true,"sound":true}}
2019/10/29 11:27:07.033845 INFO pushclient.christianpauly_push_1.0 helper output: {"notification":{"card":{"icon":"notification","body":"New messages:\n['from \"XXX\" \u003cXXX\u003e about YYY']","summary":"New mail","popup":true,"persist":true},"vibrate":true,"sound":true}}
2019/10/29 11:27:07.040529 ERROR GetWindowStack call returned org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.Unity.WindowStack was not provided by any .service files

** (process:3451): WARNING **: a source with id 'postal' doesn't exist
2019/10/29 11:27:07.460459 INFO pushclient.christianpauly_push_1.0 helper output: {"notification":{"card":{"icon":"notification","body":"New messages:\n['from \"XXX\" \u003cXXX\u003e about YYY']","summary":"New mail","popup":true,"persist":true},"vibrate":true,"sound":true}}
2019/10/29 11:27:07.536088 ERROR GetWindowStack call returned org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.Unity.WindowStack was not provided by any .service files

** (process:3451): WARNING **: a source with id 'postal' doesn't exist
2019/10/29 11:27:07.847854 INFO pushclient.christianpauly_push_1.0 helper output: {"notification":{"card":{"icon":"notification","body":"New messages:\n['from \"XXX\" \u003cXXX\u003e about YYY']","summary":"New mail","popup":true,"persist":true},"vibrate":true,"sound":true}}
2019/10/29 11:27:07.951013 ERROR GetWindowStack call returned org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.Unity.WindowStack was not provided by any .service files

** (process:3451): WARNING **: a source with id 'postal' doesn't exist
2019/10/29 11:27:08.166151 INFO pushclient.christianpauly_push_1.0 helper output: {"notification":{"card":{"icon":"notification","body":"New messages:\n['from \"XXX\" \u003cXXX\u003e about YYY']","summary":"New mail","popup":true,"persist":true},"vibrate":true,"sound":true}}
2019/10/29 11:27:08.437965 ERROR GetWindowStack call returned org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.Unity.WindowStack was not provided by any .service files

** (process:3451): WARNING **: a source with id 'postal' doesn't exist

**Comment by hallyn** [comment]
At the moment it is again behind.  I've pulled new messages down with my phone using offlineimap, so network is there.  But the notifications from ubuntu push server, which were sent 12 minutes ago, have not yet come in.

**Comment by hallyn** [comment]
Yeah so every time it happens (a few more times today), there is a message like

```
session error'ed out with read tcp 10.91.118.101:39683->188.166.175.79:5001: i/o timeout
```

I'm tempted to offer a patch to client.go:initSessionAndPoller() to make it do NewSession in a gofunc and after 60 or 90 seconds a timer aborts it...  But there must be a cleaner way.

**Comment by hallyn** [comment]
Testing 6642ac on my phone now.  Will  report back.

**Comment by hallyn** [comment]
Much better, but not good enough.  Last night I got one io  timeout during the read in client.loop().

**Comment by hallyn** [comment]
@dobey do you know the pingtimeout configured on the server?

**Comment by dobey** [comment]
> @dobey do you know the pingtimeout configured on the server?

The server code is in the same repo. I don't recall if there's any special timeouts configured. Standard TCP timeout is 10 minutes though.

**Comment by hallyn** [comment]
Right but the client seems to hang for up to an hour, so I wondered whether the server instance sets it higher.  I set a hard timeout of 50s on session creation, wondering whether I can do the same at client loop around read and write, or if that will break the protocol.

**Comment by hallyn** [comment]
I'm considering using conn .SetDeadline(), but that seems easy to do wrong as it appears all code has to update it.
(Oddly, I see that server/session/session.c is already claiming to do SetDeadline(), so there really should be no reason for this to happen)

**Comment by UniversalSuperBox** [comment]
This issue has been imported to GitLab as https://gitlab.com/ubports/core/lomiri-push-service/-/issues/22. Any further discussion should happen there.
