### ISSUE TITLE
Is a server implementation available for non-testing use?

### ISSUE THREAD

**Issue by ell1e** [ubports/ubuntu-push#31]
Is there a server implementation available for non-testing use? The way of organizing push system-wide via DBus seems pretty brilliant, but I imagine adoption in other distributions (which I get you might not be interested in, but it seems like such a nice tech to share) could be difficult unless people and distros can choose to run & use their own servers in a more federated way, if they want to. Edit: sorry if that is just what is in the `server` folder, the repo description and various README wordings sound a bit like that's just one for testing and not really code meant to run for more widely accessible use.

**Comment by Flohack74** [comment]
You can actually use the testing server, its very stable and scales pretty well. We are doing the same ^^

**Comment by Flohack74** [comment]
Its just not scaling horizontally, and has no persistence in case of power failure etc.

**Comment by dobey** [comment]
Closing this as it has been answered.
